### ISSUE TITLE
Twisted Module not found

### ISSUE THREAD

**Issue by Safwaan21** [B1naryKill3r/HQSolver#17]
when i run the main.py, I get

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from autobahn.twisted.websocket import connectWS
  File "C:\Users\Safwaan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\twisted\__init__.py", line 40, in <module>
    from autobahn.twisted.util import sleep
  File "C:\Users\Safwaan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\twisted\util.py", line 31, in <module>
    from twisted.internet.defer import Deferred
ModuleNotFoundError: No module named 'twisted.internet'

**Comment by B1naryKill3r** [comment]
Something wrong with your python environment, try reinstalling it

**Comment by B1naryKill3r** [comment]
Closed due no response
