### ISSUE TITLE
Errors while attempting to run.

### ISSUE THREAD

**Issue by Chasewhip8** [B1naryKill3r/HQSolver#21]
Had a lot of trouble getting it to run this far with all of the imports, python wasn't working, so i assumed it needed python3, 

chase@LinuxWhip ~/Desktop/HQSolver-master $ python3 main.py
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from game import GameFactory
  File "/home/chase/Desktop/HQSolver-master/game.py", line 7, in <module>
    from solver import Solver
  File "/home/chase/Desktop/HQSolver-master/solver.py", line 3, in <module>
    from solvers.gsearch import Google
  File "/home/chase/Desktop/HQSolver-master/solvers/gsearch.py", line 4, in <module>
    from google import google
  File "/home/chase/.local/lib/python3.5/site-packages/pygoogle/google.py", line 118
    %(__credits__)s""" % globals()
                     ^
SyntaxError: invalid syntax

**Comment by Chasewhip8** [comment]
Issue has been found, I am running linux mint cinamin so i can not overwrite python 3.5. I compiled it form source and did a "./configure --enable-loadable-sqlite-extensions && make && sudo make altinstall"

It was not the projects fault.

Quick question though, does my authentication key change every time or do i only have to get it once.
