### ISSUE TITLE
self.question["question"] not be string

### ISSUE THREAD

**Issue by prKassad** [B1naryKill3r/HQSolver#32]
Hi! I have next stack trace:

```
========================================= Question ========================================


                                       Question 3/12

                                                                     Category: Food & Drink


Unhandled Error
Traceback (most recent call last):
  File "\lib\site-packages\twiste
d\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "\lib\site-packages\twiste
d\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "\lib\site-packages\twiste
d\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "\lib\site-packages\twiste
d\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "\lib\site-packages\twiste
d\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "\lib\site-packages\twiste
d\internet\tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "\lib\site-packages\twiste
d\internet\tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "\lib\site-packages\twiste
d\protocols\tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "\lib\site-packages\twiste
d\protocols\tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "\lib\site-packages\twiste
d\protocols\policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "\lib\site-packages\autoba
hn\twisted\websocket.py", line 131, in dataReceived
    self._dataReceived(data)
  File "\lib\site-packages\autoba
hn\websocket\protocol.py", line 1175, in _dataReceived
    self.consumeData()
  File "\lib\site-packages\autoba
hn\websocket\protocol.py", line 1187, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "\lib\site-packages\autoba
hn\websocket\protocol.py", line 1553, in processData
    fr = self.onFrameEnd()
  File "\lib\site-packages\autoba
hn\websocket\protocol.py", line 1675, in onFrameEnd
    self._onMessageEnd()
  File "\lib\site-packages\autoba
hn\twisted\websocket.py", line 159, in _onMessageEnd
    self.onMessageEnd()
  File "\lib\site-packages\autoba
hn\websocket\protocol.py", line 627, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "\lib\site-packages\autoba
hn\twisted\websocket.py", line 162, in _onMessage
    self.onMessage(payload, isBinary)
  File "\HQSolver\game.py", line 42, in onMessage
    self.solver.solve(message)
  File "\HQSolver\solver.py", line 43, in solve
    self.showQuestion()
  File "\HQSolver\solver.py", line 137, in showQuestion
    tempPrint += self.question["question"].encode( "UTF-8" )
builtins.TypeError: must be str, not bytes

[Connection] Connection has been lost! Retrying...
```

Why self.question["question"] not be string? Any options plz.

**Comment by B1naryKill3r** [comment]
Because you're changing string to bytes

Change ``self.question["question"].encode()``
to
``self.question["question"].decode()``
