### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by JCookie20001** [B1naryKill3r/HQSolver#33]
This is probably something really dumb, but I have this issue that I cannot fix:
```Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from twisted.internet import reactor, ssl
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/ssl.py", line 59, in <module>
    from OpenSSL import SSL
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: d2i_DHxparams
```

**Comment by B1naryKill3r** [comment]
Propably because you using Python3.7 instead of Python3.6.

I designed this tool for Python3.6
