### ISSUE TITLE
Unhandled Error when game is live 

### ISSUE THREAD

**Issue by hobocow** [B1naryKill3r/HQSolver#35]
> 

                                                    Question 1/12                                                      
                                                                                                       Category: History

Unhandled Error
Traceback (most recent call last):
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\internet\tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\internet\tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\protocols\tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\protocols\tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\protocols\policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\twisted\websocket.py", line 131, in dataReceived
    self._dataReceived(data)
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\websocket\protocol.py", line 1175, in _dataReceived
    self.consumeData()
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\websocket\protocol.py", line 1187, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\websocket\protocol.py", line 1553, in processData
    fr = self.onFrameEnd()
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\websocket\protocol.py", line 1675, in onFrameEnd
    self._onMessageEnd()
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\twisted\websocket.py", line 159, in _onMessageEnd
    self.onMessageEnd()
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\websocket\protocol.py", line 627, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "C:\Users\Christophe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\twisted\websocket.py", line 162, in _onMessage
    self.onMessage(payload, isBinary)
  File "C:\Users\Christophe\Desktop\HQSolver\game.py", line 42, in onMessage
    self.solver.solve(message)
  File "C:\Users\Christophe\Desktop\HQSolver\solver.py", line 43, in solve
    self.showQuestion()
  File "C:\Users\Christophe\Desktop\HQSolver\solver.py", line 137, in showQuestion
    tempPrint += self.question["question"].encode( "UTF-8" )
builtins.TypeError: must be str, not bytes

[Connection] Connection has been lost! `Retrying...`

Much appreicated if anyone can give any help on this !

**Comment by hobocow** [comment]
changed encode to decode, still not working
