### ISSUE TITLE
Long Error After Starting

### ISSUE THREAD

**Issue by tdaddy** [B1naryKill3r/HQSolver#6]
when I go to start it up I get this error...

[Connection] Connection established!
Unhandled Error
Traceback (most recent call last):
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\internet\tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\internet\tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\protocols\tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\protocols\tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\protocols\policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\twisted\websocket.py", line 131, in dataReceived
    self._dataReceived(data)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\websocket\protocol.py", line 1175, in _dataReceived
    self.consumeData()
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\websocket\protocol.py", line 1204, in consumeData
    self.processHandshake()
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\websocket\protocol.py", line 3744, in processHandshake
    self._onOpen()
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\twisted\websocket.py", line 141, in _onOpen
    self.onOpen()
  File "C:\Users\Topher\Documents\HQSolver-master\HQSolver-master\game.py", line 21, in onOpen
    self.chat = Chat()
  File "C:\Users\Topher\Documents\HQSolver-master\HQSolver-master\chat.py", line 11, in __init__
    self.show_message = readFromConfig("Chat", "show_message")
  File "C:\Users\Topher\Documents\HQSolver-master\HQSolver-master\config.py", line 19, in readFromConfig
    value = configFile[section][parameter]
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 1233, in __getitem__
    raise KeyError(key)
builtins.KeyError: 'show_message'

any ideas what's wrong?

**Comment by B1naryKill3r** [comment]
Please show me your config.ini (without auth keys, api keys etc.. of course)

**Comment by tdaddy** [comment]
[API]
; DO NOT change anything there if you doesn't know what are you doing. DO NOT
shows_now = /shows/now

[Chat]
enable = False
show_kicked = Falseshow_message = False
show_userids = False
show_usernames = False

[GameSummary]
enable = True
show_prize = True
show_userids = True
show_usernames = True

[General]
debug_mode = True
hq_client = iOS/1.2.4 b59
server_ip = https://api-quiz.hype.space

[Login]
authorization_key = 

[Solver]
google_api_key = 
google_cse_id = 
show_advancing_players = True
show_answers = True
show_answerids = True
show_category = True
show_eliminated_players = True
show_summary = True
show_players_answers = True
show_question = True
show_questionid = True
show_question_count = True
show_question_number = True
use_naive = True
use_google = True
use_wiki = True

could it be the hq_client causing the problem? I wasn't sure where to get that from

**Comment by B1naryKill3r** [comment]
Fixed that :)
Now you should be able to launch it without problem :+1: 

The problem was that i 'hard coded' location of the `config.ini` file, and you launched bot outside bot folder. Now it should work correctly

**Comment by tdaddy** [comment]
tried it at 9 and got

[Connection] Connection established!
Unhandled Error
Traceback (most recent call last):
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\internet\tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\internet\tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\protocols\tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\protocols\tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twisted\protocols\policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\twisted\websocket.py", line 131, in dataReceived
    self._dataReceived(data)
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\websocket\protocol.py", line 1175, in _dataReceived
    self.consumeData()
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\websocket\protocol.py", line 1204, in consumeData
    self.processHandshake()
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\websocket\protocol.py", line 3744, in processHandshake
    self._onOpen()
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autobahn\twisted\websocket.py", line 141, in _onOpen
    self.onOpen()
  File "C:\Users\Topher\Documents\HQSolver-master (1)\HQSolver-master\game.py", line 21, in onOpen
    self.chat = Chat()
  File "C:\Users\Topher\Documents\HQSolver-master (1)\HQSolver-master\chat.py", line 11, in __init__
    self.show_message = readFromConfig("Chat", "show_message")
  File "C:\Users\Topher\Documents\HQSolver-master (1)\HQSolver-master\config.py", line 21, in readFromConfig
    value = configFile[section][parameter]
  File "C:\Users\Topher\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 1233, in __getitem__
    raise KeyError(key)
builtins.KeyError: 'show_message'

looks like the same error

**Comment by B1naryKill3r** [comment]
'show_kicked = Falseshow_message = False'
In your config.ini file, it should be:
'show_kicked = False
show_message = False'

Didn't noticed it :P

**Comment by tdaddy** [comment]
Oh wow, I didn't notice that either lol. I'll give that a try for the 3pm game today. Thanks.
